# Configuración de ejemplo para AdventureWorld
terrain:
  width: 30
  height: 8

rides:
  - tipo: pirate
    capacity: 15
    duration: 50
    position: [5, 3]
  - tipo: ferris
    capacity: 24
    duration: 80
    position: [15, 2]

num_patrons: 80